name: 'Publish Release'
description: 'Builds, prepares, and publishes the gemini-cli packages to npm and creates a GitHub release.'

inputs:
  release-version:
    description: 'The version to release (e.g., 0.1.11).'
    required: true
  npm-tag:
    description: 'The npm tag to publish with (e.g., latest, preview, nightly).'
    required: true
  wombat-token-core:
    description: 'The npm token for the @salesforce/codey-core package.'
    required: true
  wombat-token-cli:
    description: 'The npm token for the @google/gemini-cli package.'
    required: true
  github-token:
    description: 'The GitHub token for creating the release.'
    required: true
  dry-run:
    description: 'Whether to run in dry-run mode.'
    required: true
  release-branch:
    description: 'The branch to target for the release.'
    required: true
  previous-tag:
    description: 'The previous tag to use for generating release notes.'
    required: true
  working-directory:
    description: 'The working directory to run the steps in.'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: 'Build and Prepare Packages'
      working-directory: '${{ inputs.working-directory }}'
      run: |-
        npm run build:packages
        npm run prepare:package
      shell: 'bash'

    - name: 'Configure npm for publishing'
      uses: 'actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020'
      with:
        node-version-file: '${{ inputs.working-directory }}/.nvmrc'
        registry-url: 'https://wombat-dressing-room.appspot.com'
        scope: '@google'

    - name: 'Publish @salesforce/codey-core'
      working-directory: '${{ inputs.working-directory }}'
      env:
        NODE_AUTH_TOKEN: '${{ inputs.wombat-token-core }}'
      run: |-
        npm publish \
          --dry-run="${{ inputs.dry-run }}" \
          --workspace="@salesforce/codey-core" \
          --tag="${{ inputs.npm-tag }}"
      shell: 'bash'

    - name: 'Install latest core package'
      working-directory: '${{ inputs.working-directory }}'
      if: '${{ inputs.dry-run == "false" }}'
      run: |-
        npm install "@salesforce/codey-core@${{ inputs.release-version }}" \
        --workspace="@google/gemini-cli" \
        --save-exact
      shell: 'bash'

    - name: 'Publish @google/gemini-cli'
      working-directory: '${{ inputs.working-directory }}'
      env:
        NODE_AUTH_TOKEN: '${{ inputs.wombat-token-cli }}'
      run: |-
        npm publish \
          --dry-run="${{ inputs.dry-run }}" \
          --workspace="@google/gemini-cli" \
          --tag="${{ inputs.npm-tag }}"
      shell: 'bash'

    - name: 'Bundle'
      working-directory: '${{ inputs.working-directory }}'
      run: 'npm run bundle'
      shell: 'bash'

    - name: 'Create GitHub Release'
      working-directory: '${{ inputs.working-directory }}'
      if: '${{ inputs.dry-run == "false" }}'
      env:
        GITHUB_TOKEN: '${{ inputs.github-token }}'
      run: |-
        gh release create "v${{ inputs.release-version }}" \
          bundle/gemini.js \
          --target "${{ inputs.release-branch }}" \
          --title "Release v${{ inputs.release-version }}" \
          --notes-start-tag "${{ inputs.previous-tag }}" \
          --generate-notes
      shell: 'bash'
