blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/salesforcecli/codey/discussions/new?category=ideas
    about: Feature requests should be opened as discussions
